(() => {
  const VERSION='0.9.2';
  const clip=(x,a,b)=>Math.max(a,Math.min(b,x));
  const softmax=(xs)=>{const mx=Math.max(...xs),e=xs.map(x=>Math.exp(x-mx)),z=e.reduce((a,b)=>a+b,0);return e.map(x=>x/z)};
  function leagueDrawRate(ms){const x=(ms||[]).filter(m=>Number.isFinite(m.hs)&&Number.isFinite(m.as));return (x.filter(m=>m.hs===m.as).length+3)/(x.length+12)}
  function prob({hs,as,hv,av,rh,ra,h2hHome=.5,h2hAway=.5,drawRate=.27,s=0}){const fh=hs.ppg/3,fa=as.ppg/3,vh=hv.n?hv.ppg/3:fh,va=av.n?av.ppg/3:fa,ed=(rh-ra)/400,sh=1.05*fh+.35*hs.g-.28*hs.a+.22*vh+.70*ed+.07*h2hHome+.18,sa=1.05*fa+.35*as.g-.28*as.a+.20*va-.70*ed+.07*h2hAway,close=1-clip(Math.abs(sh-sa)/2.2,0,1),tempo=(hs.g+as.g+hs.a+as.a)/4,low=1-clip((tempo-1.15)/1.25,0,1),old=.56+.44*close-.08*((hs.g+as.g)/2),neu=.60+.52*close+.65*(drawRate-.27)+.10*low-.07*((hs.g+as.g)/2);return softmax([sh,old+(neu-old)*s,sa])}
  function elo(r,m){const K=22,ha=55,rh=r.get(m.homeId)??1500,ra=r.get(m.awayId)??1500,eh=1/(1+Math.pow(10,(ra-(rh+ha))/400)),sh=m.hs>m.as?1:m.hs===m.as?.5:0,d=K*Math.log(Math.max(1,Math.abs(m.hs-m.as))+1)*1.25*(sh-eh);r.set(m.homeId,rh+d);r.set(m.awayId,ra-d)}
  const stat=()=>({n:0,ok:0,b:0,l:0,c:[[0,0,0],[0,0,0],[0,0,0]]});
  function add(o,p,y){const pr=p.indexOf(Math.max(...p)),yy=[0,0,0];yy[y]=1;o.n++;o.ok+=pr===y;o.b+=((p[0]-yy[0])**2+(p[1]-yy[1])**2+(p[2]-yy[2])**2)/3;o.l+=-Math.log(Math.max(1e-6,p[y]));o.c[y][pr]++}
  function rate(c,k=1){const tp=c[k][k],sup=c[k].reduce((a,b)=>a+b,0),fp=c.reduce((z,row,i)=>z+(i===k?0:row[k]),0),rec=tp/Math.max(1,sup),pre=tp/Math.max(1,tp+fp);return{pre,rec,f1:pre+rec?2*pre*rec/(pre+rec):0}}
  function base(past){let h=1,d=1,a=1;past.forEach(m=>m.hs>m.as?h++:m.hs===m.as?d++:a++);const z=h+d+a;return[h/z,d/z,a/z]}
  function evalFine(){const min=+$('btMin').value,N=+$('btN').value,strengths=Array.from({length:13},(_,i)=>i*.05),vars=strengths.map(s=>({id:'s'+iSafe(s),s,name:`${Math.round(s*100)}%`}));vars.push({id:'base',base:true,name:'Baseline'});const out=new Map(vars.map(v=>[v.id,stat()])),ord=[...A.matches].sort((a,b)=>a.date.localeCompare(b.date)),past=[],ratings=new Map();[...A.teams.keys()].forEach(id=>ratings.set(id,1500));for(const m of ord){const hm=past.filter(x=>x.homeId===m.homeId||x.awayId===m.homeId).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,N),am=past.filter(x=>x.homeId===m.awayId||x.awayId===m.awayId).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,N);if(hm.length>=min&&am.length>=min){const y=m.hs>m.as?0:m.hs===m.as?1:2;for(const v of vars){let pp;if(v.base)pp=base(past);else{const hs=weightedStats(hm,m.homeId,.94),as=weightedStats(am,m.awayId,.94),hv=weightedStats(hm.filter(x=>x.homeId===m.homeId),m.homeId,.94),av=weightedStats(am.filter(x=>x.awayId===m.awayId),m.awayId,.94),h2=past.filter(x=>(x.homeId===m.homeId&&x.awayId===m.awayId)||(x.homeId===m.awayId&&x.awayId===m.homeId)).slice(-5);let hw=0,aw=0;h2.forEach(x=>{if(x.hs===x.as)return;if((x.homeId===m.homeId&&x.hs>x.as)||(x.awayId===m.homeId&&x.as>x.hs))hw++;else aw++});pp=prob({hs,as,hv,av,rh:ratings.get(m.homeId)||1500,ra:ratings.get(m.awayId)||1500,h2hHome:h2.length?hw/h2.length:.5,h2hAway:h2.length?aw/h2.length:.5,drawRate:leagueDrawRate(past),s:v.s})}add(out.get(v.id),pp,y)}}elo(ratings,m);past.push(m)}return vars.map(v=>{const o=out.get(v.id),rx=rate(o.c);return{...v,n:o.n,acc:o.ok/Math.max(1,o.n),b:o.b/Math.max(1,o.n),l:o.l/Math.max(1,o.n),...rx,c:o.c}})}
  function iSafe(s){return Math.round(s*100)}
  function run(){if(!A?.matches?.length){$('btResult').innerHTML='<div class="card"><div class="notice warning">Najpierw pobierz dane.</div></div>';return}const r=evalFine(),baseline=r.find(x=>x.base),cand=r.filter(x=>!x.base),minB=Math.min(...cand.map(x=>x.b)),minL=Math.min(...cand.map(x=>x.l)),tolB=.0005,tolL=.003;const eligible=cand.filter(x=>x.b<=minB+tolB&&x.l<=minL+tolL),best=[...eligible].sort((a,b)=>b.f1-a.f1||a.b-b.b)[0],pure=[...cand].sort((a,b)=>a.b-b.b||a.l-b.l)[0];const rows=r.map(x=>`<tr class="${x===best?'sweepBest':''}"><td>${x.base?'Baseline ligi':'Draw boost '+x.name}${x===best?' ★':''}</td><td>${x.n}</td><td>${(x.acc*100).toFixed(1)}%</td><td>${x.b.toFixed(4)}</td><td>${x.l.toFixed(4)}</td><td>${x.base?'—':(x.pre*100).toFixed(1)+'%'}</td><td>${x.base?'—':(x.rec*100).toFixed(1)+'%'}</td><td>${x.base?'—':(x.f1*100).toFixed(1)+'%'}</td><td>${(x.b-baseline.b)>=0?'+':''}${(x.b-baseline.b).toFixed(4)}</td></tr>`).join('');$('btResult').innerHTML=`<div class="card"><h3>Laboratorium modelu 0.9.2 — dokładny sweep 0–60%</h3><div class="notice good"><b>Kandydat kompromisowy:</b> Draw boost ${best.name}. Brier ${best.b.toFixed(4)}, log ${best.l.toFixed(4)}, Recall X ${(best.rec*100).toFixed(1)}%, F1 X ${(best.f1*100).toFixed(1)}%. Czyste minimum Brier: ${pure.name} (${pure.b.toFixed(4)}).</div><div class="sweepScroll" style="margin-top:12px"><table class="sweepTable"><thead><tr><th>Wariant</th><th>Mecze</th><th>1/X/2</th><th>Brier ↓</th><th>Log ↓</th><th>Precision X</th><th>Recall X</th><th>F1 X</th><th>Δ Brier vs base</th></tr></thead><tbody>${rows}</tbody></table></div></div><div class="card"><div class="notice warning"><b>Reguła wyboru 0.9.2:</b> najpierw odrzucamy warianty gorsze od najlepszego o więcej niż 0.0005 Brier lub 0.003 log loss, a wśród pozostałych wybieramy najwyższe F1 remisu. To kompromis do walidacji na innych ligach — nie finalny parametr 1.0.</div></div>`}
  function upgrade(){const v=document.querySelector('.top h1 .muted');if(v)v.textContent=VERSION;const sub=document.querySelector('.top .sub');if(sub)sub.textContent='Model Lab 0.9.2 — dokładny sweep remisów co 5 pp i wybór kompromisu Brier/log loss/F1.';const b=$('runBacktest');if(b){b.textContent='Uruchom dokładny sweep 0.9.2';b.onclick=run}const t=b?.closest('.card')?.querySelector('h3');if(t)t.textContent='Backtest i dokładne strojenie remisów 0.9.2'}
  upgrade();
})();