(() => {
 const VERSION='0.9.5',CUPS=[['CL','Champions League'],['EL','Europa League'],['UCL','Conference League']];
 const sleep=ms=>new Promise(r=>setTimeout(r,ms));
 function style(){const s=document.createElement('style');s.textContent=`.cup95{margin-top:12px;padding-top:12px;border-top:1px solid var(--line)}.cup95Checks{display:flex;gap:8px;flex-wrap:wrap;margin:9px 0}.cup95Check{display:flex;gap:6px;align-items:center;border:1px solid var(--line);padding:7px 9px;border-radius:9px}.cup95Table{width:100%;border-collapse:collapse;font-size:12px}.cup95Table th,.cup95Table td{padding:8px;border-bottom:1px solid var(--line);text-align:right}.cup95Table th:first-child,.cup95Table td:first-child{text-align:left}`;document.head.appendChild(s)}
 const valid=m=>m.status==='FINISHED'&&Number.isFinite(m.score?.fullTime?.home)&&Number.isFinite(m.score?.fullTime?.away);
 const norm=m=>({id:String(m.id),date:(m.utcDate||'').slice(0,10),homeId:String(m.homeTeam?.id||''),awayId:String(m.awayTeam?.id||''),home:m.homeTeam?.name||'',away:m.awayTeam?.name||'',hs:m.score?.fullTime?.home,as:m.score?.fullTime?.away,competition:m.competition?.code||''});
 async function req(q,retry=0){const r=await fetch('/api/football?'+new URLSearchParams(q));let d;try{d=await r.json()}catch{d={error:'Nieprawidłowa odpowiedź backendu.'}}if(r.status===429&&retry<2){await sleep(6500*(retry+1));return req(q,retry+1)}if(!r.ok)throw Error(d.error||('HTTP '+r.status));return d}
 async function cupMatches(code,season){return req({action:'matches',competition:code,season:String(season),includePrevious:'0'})}
 async function history(teamId,before){const end=new Date(before+'T00:00:00Z');end.setUTCDate(end.getUTCDate()-1);const start=new Date(end);start.setUTCDate(start.getUTCDate()-300);return req({action:'teamHistory',teamId:String(teamId),dateFrom:start.toISOString().slice(0,10),dateTo:end.toISOString().slice(0,10),limit:'60'})}
 function teamStat(ms,id,N=8){const x=ms.filter(m=>m.homeId===id||m.awayId===id).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,N);if(!x.length)return null;let pts=0,gf=0,ga=0;for(const m of x){const home=m.homeId===id,f=home?m.hs:m.as,a=home?m.as:m.hs;gf+=f;ga+=a;pts+=f>a?3:f===a?1:0}return{n:x.length,ppg:pts/x.length,gf:gf/x.length,ga:ga/x.length}}
 function pred(h,a){const diff=(h.ppg-a.ppg)*.75+(h.gf-a.gf)*.25-(h.ga-a.ga)*.18+.16,e=[Math.exp(diff),Math.exp(.48-Math.abs(diff)*.34),Math.exp(-diff)],z=e.reduce((x,y)=>x+y,0);return e.map(x=>x/z)}
 function metric(rows){let b=0,l=0,ok=0;for(const r of rows){const y=r.y,p=r.p,yy=[0,0,0];yy[y]=1;b+=p.reduce((z,v,i)=>z+(v-yy[i])**2,0)/3;l+=-Math.log(Math.max(1e-6,p[y]));ok+=p.indexOf(Math.max(...p))===y}return{n:rows.length,b:b/Math.max(1,rows.length),l:l/Math.max(1,rows.length),acc:ok/Math.max(1,rows.length)}}
 async function run(){const box=$('btResult'),season=+$('season').value,chosen=CUPS.filter(([c])=>document.getElementById('cup95_'+c)?.checked);if(!chosen.length){box.innerHTML='<div class="card"><div class="notice warning">Wybierz co najmniej jeden puchar.</div></div>';return}box.innerHTML='<div class="card"><h3>European Cup Lab 0.9.5</h3><div id="cup95status" class="status">Start…</div></div>';const all=[];for(const[code,name]of chosen){try{const d=await cupMatches(code,season),ms=(d.matches||[]).filter(valid).map(norm).sort((a,b)=>a.date.localeCompare(b.date)),test=ms.slice(Math.floor(ms.length*.55)),rows=[];for(let i=0;i<test.length;i++){$('cup95status').textContent=`${name}: ${i+1}/${test.length} — historia ligowa drużyn…`;const m=test[i];try{const[hh,aa]=await Promise.all([history(m.homeId,m.date),history(m.awayId,m.date)]),hm=(hh.matches||[]).filter(valid).map(norm),am=(aa.matches||[]).filter(valid).map(norm),hs=teamStat(hm,m.homeId),as=teamStat(am,m.awayId);if(hs&&as&&hs.n>=5&&as.n>=5)rows.push({y:m.hs>m.as?0:m.hs===m.as?1:2,p:pred(hs,as)})}catch{}if(i<test.length-1)await sleep(700)}all.push({name,...metric(rows),test:test.length})}catch(e){all.push({name,error:e.message})}}
 const ok=all.filter(x=>!x.error&&x.n),n=ok.reduce((z,x)=>z+x.n,0),B=n?ok.reduce((z,x)=>z+x.b*x.n,0)/n:0,L=n?ok.reduce((z,x)=>z+x.l*x.n,0)/n:0,A=n?ok.reduce((z,x)=>z+x.acc*x.n,0)/n:0;box.innerHTML=`<div class="card"><h3>European Cup Lab 0.9.5 — historia między rozgrywkami</h3><div class="notice ${n?'good':'warning'}"><b>${n} prognoz pucharowych z pełniejszą historią.</b>${n?` Brier ${B.toFixed(4)} • log ${L.toFixed(4)} • 1/X/2 ${(A*100).toFixed(1)}%.`:''}</div><p class="muted">Dla każdego meczu pobieramy wcześniejsze mecze obu drużyn także spoza pucharu. Dane po dacie analizowanego meczu nie są używane.</p><table class="cup95Table"><thead><tr><th>Rozgrywki</th><th>Prognozy/test</th><th>Pokrycie</th><th>Brier</th><th>Log</th><th>1/X/2</th></tr></thead><tbody>${all.map(x=>x.error?`<tr><td>${x.name}</td><td colspan="5">${x.error}</td></tr>`:`<tr><td>${x.name}</td><td>${x.n}/${x.test}</td><td>${(100*x.n/Math.max(1,x.test)).toFixed(0)}%</td><td>${x.b.toFixed(4)}</td><td>${x.l.toFixed(4)}</td><td>${(x.acc*100).toFixed(1)}%</td></tr>`).join('')}</tbody></table></div><div class="card"><div class="notice warning"><b>0.9.5 to laboratorium pucharowe, nie finalny model.</b> Najpierw sprawdzamy, czy historia drużyny ze wszystkich dostępnych rozgrywek rozwiązuje problem małej próbki Champions/Europa/Conference. Następny krok to włączenie tej historii do głównego Elo/modelu, jeśli wynik i pokrycie będą sensowne.</div></div>`}
 function upgrade(){const v=document.querySelector('.top h1 .muted');if(v)v.textContent=VERSION;const sub=document.querySelector('.top .sub');if(sub)sub.textContent='European Cup Lab — historia drużyn między rozgrywkami bez look-ahead.';const btn=$('runBacktest');if(!btn)return;const host=btn.closest('.card'),d=document.createElement('div');d.className='cup95';d.innerHTML='<h4>European Cup Lab 0.9.5</h4><div class="muted">Osobny test pucharów z historią zespołów także z lig krajowych.</div><div class="cup95Checks">'+CUPS.map(([c,n])=>`<label class="cup95Check"><input id="cup95_${c}" type="checkbox" ${c==='CL'?'checked':''}> ${n}</label>`).join('')+'</div><button id="cup95run" type="button">Uruchom European Cup Lab 0.9.5</button>';host.appendChild(d);$('cup95run').onclick=run}
 style();upgrade();
})();